# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Command-line interface for SQLite
brew "sqlite"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Console Matrix
brew "cmatrix"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Dynamic menu for X11
brew "dmenu"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Isolated development environments using Docker
brew "docker-compose"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line tools for fly.io services
brew "flyctl"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Run and Test HTTP Requests with plain text and curl
brew "hurl"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Simple terminal UI for git commands
brew "lazygit"
# Library for encoding and decoding .avif files
brew "libavif"
# Powerful, lightweight programming language
brew "lua"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Open source relational database management system
brew "mysql", restart_service: :changed
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# CLI for NextDNS's DNS-over-HTTPS (DoH)
brew "nextdns"
# Platform built on V8 to build network applications
brew "node"
# Tools for one-time password authentication systems
brew "oath-toolkit"
# Object-relational database system
brew "postgresql@17", restart_service: :changed
# Persistent key-value database, with built-in net interface
brew "redis", restart_service: :changed
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Rust toolchain installer
brew "rustup"
# User interface to the TELNET protocol
brew "telnet"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Internet file retriever
brew "wget"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Enable Windows-like alt-tab
cask "alt-tab"
# Application uninstaller
cask "appcleaner"
# Desktop password and login vault
cask "bitwarden"
# Open source IDE for exploring and testing APIs
cask "bruno"
# Write, edit, and chat about your code with AI
cask "cursor"
# Voice and text chat software
cask "discord"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Desktop client for Filen.io
cask "filen"
# Web browser
cask "firefox@nightly"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Web browser
cask "google-chrome@canary"
# Open-source screen recorder built with web technology
cask "kap"
# Tool to prevent the system from going into sleep mode
cask "keepingyouawake"
# File archiver
cask "keka"
# Customise mouse behavior
cask "linearmouse"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Open-source software for live streaming and screen recording
cask "obs"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Replacement for Docker Desktop
cask "orbstack"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Control your tools with a few keystrokes
cask "raycast"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Web browser
cask "safari-technology-preview"
# Screenshot measurement and annotation tool
cask "shottr"
# Instant messaging application focusing on security
cask "signal"
# Team communication and collaboration software
cask "slack"
# Messaging app with a focus on speed and security
cask "telegram"
# Multiplayer code editor
cask "zed"
# Video communication and virtual meeting platform
cask "zoom"

